[package]
name = "near-vm-runner-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "This crate contains primitive types for vm-runner."
repository.workspace = true
license.workspace = true
categories = ["wasm"]
publish = true

[lints]
workspace = true

[dependencies]
borsh.workspace = true
tracing.workspace = true
bytesize.workspace = true
bn.workspace = true
thiserror.workspace = true
stdx.workspace = true
strum.workspace = true
sha3.workspace = true
sha2.workspace = true
ed25519-dalek.workspace = true
ripemd.workspace = true
serde.workspace = true
lru.workspace = true
tempfile.workspace = true
enum-map.workspace = true
num-rational.workspace = true
rustix.workspace = true
once_cell.workspace = true

near-crypto.workspace = true
near-parameters.workspace = true
near-primitives-core.workspace = true
